/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthCamp;
import HappyPawSystem.Ecosystem;
import HappyPawSystem.PetVolunteer.PetVolunteerDirectory;
import HappyPawSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author rashmisingh
 */
public class MainPageOrganiser extends javax.swing.JPanel {

    /**
     * Creates new form MainPageOrganiser
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;
    private PetVolunteerDirectory petVolunteerDirectory;

    public MainPageOrganiser(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.petVolunteerDirectory = petVolunteerDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        sidepane = new javax.swing.JPanel();
        manageorginfo = new javax.swing.JPanel();
        lblmanageorginfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        managepetvol = new javax.swing.JPanel();
        lblManagePetVolunteer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        sidepane.setBackground(new java.awt.Color(63, 40, 101));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageorginfo.setBackground(new java.awt.Color(187, 177, 205));
        manageorginfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblmanageorginfo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblmanageorginfo.setForeground(new java.awt.Color(54, 34, 86));
        lblmanageorginfo.setText("MANAGE ORGANISATION INFO");
        lblmanageorginfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageorginfoMousePressed(evt);
            }
        });
        manageorginfo.add(lblmanageorginfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 22));
        manageorginfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        sidepane.add(manageorginfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 40));

        managepetvol.setBackground(new java.awt.Color(187, 177, 205));
        managepetvol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManagePetVolunteer.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblManagePetVolunteer.setForeground(new java.awt.Color(54, 34, 86));
        lblManagePetVolunteer.setText("MANAGE PET VOLUNTEERS");
        lblManagePetVolunteer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblManagePetVolunteerMousePressed(evt);
            }
        });
        managepetvol.add(lblManagePetVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 24));
        managepetvol.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        sidepane.add(managepetvol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(63, 40, 101));
        sidepane.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-05-01 at 11.11.38 PM (1) copy.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblmanageorginfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageorginfoMousePressed
        // TODO add your handling code here:
        ManageOrgInfo manageOrgInfoJPanel = new ManageOrgInfo(userProcessContainer, account, system);
        userProcessContainer.add("ManageOrgInfo", manageOrgInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lblmanageorginfoMousePressed

    private void lblManagePetVolunteerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagePetVolunteerMousePressed
        // TODO add your handling code here:
        ManagePetVolunteer managePetVolunteerJPanel = new ManagePetVolunteer(userProcessContainer, account, system);
        userProcessContainer.add("ManageOrgInfo", managePetVolunteerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lblManagePetVolunteerMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblManagePetVolunteer;
    private javax.swing.JLabel lblmanageorginfo;
    private javax.swing.JPanel manageorginfo;
    private javax.swing.JPanel managepetvol;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
