/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Driver;

import ReliefSystem.Driver.Driver;
import ReliefSystem.Ecosystem;
import ReliefSystem.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jsher
 */
public class DriverWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;
    
    public DriverWorkArea(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldriver = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnchangestatus = new javax.swing.JButton();

        tbldriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet type", "Health Camp", "Hospital Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbldriver);

        jLabel1.setText("Status");

        btnchangestatus.setText("Change Status");
        btnchangestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnchangestatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnchangestatus)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangestatusActionPerformed
        // TODO add your handling code here:
        
        for(Driver driver: system.getDriverDirectory().getDriverDirectory()) {
            if(account.getUsername().equals(driver.getUsername())) {
                system.getDriverDirectory().updateDropOffStatus(driver,txtStatus.getText());
            }
        }
        populateTable();
    }                                               

    public void populateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tbldriver.getModel();
        tablemodel.setRowCount(0);
        for(Driver driver: system.getDriverDirectory().getDriverDirectory()) {
            if(account.getUsername().equals(driver.getUsername())) {
                Object[] row = new Object[5];
                row[0] = driver.getPetOwner();
                row[1] = driver.getPetType();
                row[2] = driver.getHealthCamp();
                row[3] = driver.getHospitalName();
                row[4] = driver.getDropOffStatus() == null ? "N/A" : driver.getDropOffStatus();
                tablemodel.addRow(row);
            }
        }
    }//GEN-LAST:event_btnchangestatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangestatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldriver;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}