/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Fundraiser;
import HappyPawSystem.Ecosystem;
import HappyPawSystem.FundRaising.FundRaising;
import HappyPawSystem.Sponsor.Sponsor;
import HappyPawSystem.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rashmisingh
 */
public class FundraiserWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form FundraiserWorkArea
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;
    public FundraiserWorkArea(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        populateFundRaisingTable();
    }

    
    public void populateFundRaisingTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblfundraiser.getModel();

        tablemodel.setRowCount(0);
        for (UserAccount user : system.getUserAccountDirectory().getUserAccountList()) {
            
        }
        for(FundRaising fundRaising: system.getFundRaisingDirectory().getFundRaisingDirectory()){
             Object[] row = new Object[5];
                row[0] = fundRaising;
                row[1] = fundRaising.getPetOwner();
                row[2] = fundRaising.getPetType();
                row[3] = fundRaising.getHealthCamp();
                row[4] = fundRaising.getSponsorStatus() == null ? "N/A" : fundRaising.getSponsorStatus();
                tablemodel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblfundraiser = new javax.swing.JTable();
        btnAddSponsor = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 209, 222));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblfundraiser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fundraiser Name", "Pet Owner", "Pet Type", "Health Camp", "Sponsor Status"
            }
        ));
        jScrollPane1.setViewportView(tblfundraiser);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 560, 90));

        btnAddSponsor.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnAddSponsor.setForeground(new java.awt.Color(63, 40, 101));
        btnAddSponsor.setText("ADD SPONSOR");
        btnAddSponsor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSponsorActionPerformed(evt);
            }
        });
        add(btnAddSponsor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSponsorActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblfundraiser.getSelectedRow();
        FundRaising fundRaiserSelected = (FundRaising) tblfundraiser.getValueAt(selectedRow, 0);
        for(Sponsor sponsor: system.getSponsorDirectory().getSponsorDirectory()) {
            system.getSponsorDirectory().updateSponsorPetOwnerInfo(sponsor, fundRaiserSelected.getPetOwner(), fundRaiserSelected.getPetType(), fundRaiserSelected.getHealthCamp(), fundRaiserSelected.getHospitalName());
            System.out.println("Sponsor has been added successfully");
        }
        JOptionPane.showMessageDialog(this, "Request has been sent to the sponsor");
    }//GEN-LAST:event_btnAddSponsorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSponsor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfundraiser;
    // End of variables declaration//GEN-END:variables
}
