/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hospital;


import HappyPawSystem.Ecosystem;
import HappyPawSystem.LabAssistant.LabAssistant;
import HappyPawSystem.PetVolunteer.PetVolunteer;
import HappyPawSystem.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author haarikakatlaparthi
 */
public class LabAssistantWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantWorkArea
     */
    
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;
    
    public LabAssistantWorkArea(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tbllabassitant.getModel();
        tablemodel.setRowCount(0);
        for (LabAssistant labAssistant : system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            if (labAssistant.getUsername().equals(account.getUsername())) {
                System.out.println("Lab assistant : " + labAssistant.getUsername());
                System.out.println("Lab assistant : " + labAssistant.getPetOwner());
                System.out.println("Lab assistant : " + labAssistant.getPetType());
                Object[] row = new Object[4];
                row[0] = labAssistant.getPetOwner();
                row[1] = labAssistant.getPetType();
                row[2] = labAssistant.getHealthCamp();
                row[3] = labAssistant.getLabResultStatus() == null ? "N/A" : labAssistant.getLabResultStatus();
                tablemodel.addRow(row);
            }

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllabassitant = new javax.swing.JTable();
        lbllabresult = new javax.swing.JLabel();
        txtlabresult = new javax.swing.JTextField();
        btnchangestatus = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 209, 222));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 40, 101));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME LAB ASSISTANT");

        tbllabassitant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet Type", "Health Camp", "Test Result"
            }
        ));
        jScrollPane1.setViewportView(tbllabassitant);

        lbllabresult.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbllabresult.setForeground(new java.awt.Color(63, 40, 101));
        lbllabresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllabresult.setText("LAB RESULT");

        txtlabresult.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));

        btnchangestatus.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnchangestatus.setForeground(new java.awt.Color(63, 40, 101));
        btnchangestatus.setText("CHANGE STATUS");
        btnchangestatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnchangestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbllabresult, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtlabresult, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnchangestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbllabresult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlabresult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnchangestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangestatusActionPerformed
        // TODO add your handling code here:
        String status = txtlabresult.getText();
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            system.getLabAssistantDirectory().updateLabAssistantTestResult(labAssistant, status);
            System.out.println("Lab result has been updated successfully");
        }
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            for(PetVolunteer petVolunteer: system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
                if(petVolunteer.getName().equals(labAssistant.getPetOwner())){
                    system.getPetVolunteerDirectory().updatePetVolunteerLabStatus(petVolunteer, status);
                    System.out.println("Lab status has been updated successfully");
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Lab results has been updated successfully ");
        populateTable();
    }//GEN-LAST:event_btnchangestatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangestatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllabresult;
    private javax.swing.JTable tbllabassitant;
    private javax.swing.JTextField txtlabresult;
    // End of variables declaration//GEN-END:variables
}
