/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hospital;

import HappyPawSystem.Ecosystem;
import HappyPawSystem.LabAssistant.LabAssistant;
import HappyPawSystem.PetVolunteer.PetVolunteer;
import HappyPawSystem.Vet.Vet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author haarikakatlaparthi
 */
public class VetWorkarea extends javax.swing.JPanel {

    /**
     * Creates new form VetWorkarea
     */
    
    JPanel userProcessContainer;
    Ecosystem system;
    
    public VetWorkarea(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateVetTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVetPetOwners = new javax.swing.JTable();
        btnFurtherExaminationLab = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblManageInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 209, 222));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVetPetOwners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vet Name", "Pet Owner", "Pet Type", "Health Camp"
            }
        ));
        jScrollPane1.setViewportView(tblVetPetOwners);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 640, 116));

        btnFurtherExaminationLab.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnFurtherExaminationLab.setForeground(new java.awt.Color(63, 40, 101));
        btnFurtherExaminationLab.setText("ASSIGN LAB");
        btnFurtherExaminationLab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFurtherExaminationLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFurtherExaminationLabActionPerformed(evt);
            }
        });
        add(btnFurtherExaminationLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 139, 32));

        jPanel1.setBackground(new java.awt.Color(63, 40, 101));

        lblManageInfo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblManageInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblManageInfo.setText("LAB ASSISTANT WORK AREA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(lblManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFurtherExaminationLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFurtherExaminationLabActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVetPetOwners.getSelectedRow();
        Vet vetSelected = (Vet) tblVetPetOwners.getValueAt(selectedRow, 0);
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            for(Vet vet: system.getVetDirectory().getVetDirectory()) {
                if(vet.getHospitalName().equals(labAssistant.getHospitalName())) {
                    System.out.println("selected vet : " + vetSelected.getUsername() + " " + vetSelected.getHealthCamp());
                    system.getLabAssistantDirectory().updateLabAssistantInfo(labAssistant, vetSelected.getUsername(), vetSelected.getPetOwner(),vetSelected.getPetType(),vetSelected.getHealthCamp());
                    System.out.println("Lab assistant has been assigned");
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Lab assistant has been assigned successfully");
    }//GEN-LAST:event_btnFurtherExaminationLabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFurtherExaminationLab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageInfo;
    private javax.swing.JTable tblVetPetOwners;
    // End of variables declaration//GEN-END:variables


private void populateVetTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblVetPetOwners.getModel();
        for(PetVolunteer petVolunteer : system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
            for(Vet vet: system.getVetDirectory().getVetDirectory()) {
                System.out.println("pet volunteer hosp name : " + petVolunteer.getHospitalName() );
                System.out.println("vet hosp name : " + vet.getHospitalName() );
                if(vet.getHospitalName().equals(petVolunteer.getHospitalName())){
                    Object[] row = new Object[4];
                    row[0] = vet;
                    row[1] = vet.getPetOwner();
                    row[2] = vet.getPetType();
                    row[3] = vet.getHealthCamp();
                    tablemodel.addRow(row);
                }
            }
        }
    }


}
